# coding: utf-8
# Generated by Django 2.0.3 on 2018-06-25 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = []

    dependencies = [
        ('main', '0011_categorization_labeling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('status', models.CharField(default='CREATED', max_length=10)),
                ('file_format', models.CharField(max_length=13)),
                ('compartment', models.CharField(
                    choices=[('0', 'N/A'), ('1', 'Intracellular/Cytosol (Cy)'),
                             ('2', 'Extracellular')], default='0',
                    help_text='Compartment of the cell for this Measurement.', max_length=1,
                    verbose_name='Compartment')),
                ('object_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                    parent_link=True, primary_key=True,
                                                    related_name='+', serialize=False,
                                                    to='main.EDDObject')),
            ],
            options={
                'db_table': 'import',
            },
            bases=('main.eddobject',),
        ),
        migrations.CreateModel(
            name='ImportCategory',
            fields=[
                ('object_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                    parent_link=True, primary_key=True,
                                                    related_name='+', serialize=False,
                                                    to='main.EDDObject')),
                ('display_order', models.PositiveSmallIntegerField(
                    help_text='Relative order this category is displayed in during import',
                    unique=True, verbose_name='Display order')),
                ('protocols', models.ManyToManyField(db_table='category_protocols',
                                                     help_text='Protocols that appear in this '
                                                               'import category',
                                                     related_name='import_category',
                                                     to='main.Protocol',
                                                     verbose_name='Protocols')),
            ],
            options={
                'verbose_name_plural': 'Import Categories',
                'db_table': 'import_category',
            },
            bases=('main.eddobject',),
        ),
        migrations.AddField(
            model_name='import',
            name='category',
            field=models.ForeignKey(help_text='The user-selected data category for this import',
                                    on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                    to='edd_file_importer.ImportCategory',
                                    verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='import',
            name='protocol',
            field=models.ForeignKey(help_text='The protocol for imported data',
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='main.Protocol', verbose_name='Protocol'),
        ),
        migrations.AddField(
            model_name='import',
            name='study',
            field=models.ForeignKey(help_text='The Study containing this Import',
                                    on_delete=django.db.models.deletion.CASCADE, to='main.Study',
                                    verbose_name='Study'),
        ),
        migrations.AddField(
            model_name='import',
            name='x_units',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='+', to='main.MeasurementUnit'),
        ),
        migrations.AddField(
            model_name='import',
            name='y_units',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='+', to='main.MeasurementUnit'),
        ),
        migrations.CreateModel(
            name='ImportFormat',
            fields=[
                ('eddobject_ptr', models.OneToOneField(auto_created=True,
                                                       on_delete=django.db.models.deletion.CASCADE,
                                                       parent_link=True, primary_key=True,
                                                       serialize=False, to='main.EDDObject')),
                ('parser_class', models.CharField(help_text='Name of this object.', max_length=255,
                                                  verbose_name='Name')),
            ],
            options={
                'db_table': 'import_format',
            },
            bases=('main.eddobject',),
        ),
        migrations.AlterField(
            model_name='import',
            name='file_format',
            field=models.ForeignKey(help_text='The file format for this import',
                                    on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                    to='edd_file_importer.ImportFormat', verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='import',
            name='status',
            field=models.CharField(default='Created', max_length=10),
        ),
        migrations.AddField(
            model_name='importcategory',
            name='file_formats',
            field=models.ManyToManyField(
                db_table='category_formats',
                help_text='Supported input formats for this import category',
                related_name='import_category',
                to='edd_file_importer.ImportFormat',
                verbose_name='File formats'),
        ),
    ]
